logging:
  level:
    com.example.backend: DEBUG

app:
  keycloak:
    server-url: http://172.18.69.6:8080
    realm-name: app
    clients:
      - id: frontend-web
        redirect-url: http://172.18.69.2:3000/*
    users:
      - username: admin
        password: admin
        roles:
          - MANAGER
      - username: user
        password: user
        roles:
          - USER
